ignore: make 'log' an optional dep
BurntSushi/ripgrep pull request #1910
Opened 2021-06-24 04:36 UTC by SergioBenitez

As in the title. Would be nice to avoid the dependency when `log` isn't being used. Made it a default so logs remain when updating the crate.

As an aside, does the `simd-accel` feature do anything in `globset`?

2021-06-24 11:56 UTC, BurntSushi commented
I'm not so sure about this. `globset` isn't exactly a dependency-slim crate itself. `log` is itself small and ubiquitous. Where is `globset` being used that `log` isn't?

As a downside, this infects every logging statement to the point of requiring conditional compilation. We could define our own logging macros to paper over this, but the juice really doesn't seem worth the squeeze given the number of other deps that `globset` already has.

> As an aside, does the `simd-accel` feature do anything in `globset`?

No. It used to. I probably should have added a note saying that it was left behind for backwards compatibility. `globset` hasn't had a semver bump in quite some time.

2021-06-24 11:59 UTC, SergioBenitez commented
> I'm not so sure about this. `globset` isn't exactly a dependency-slim crate itself. `log` is itself small and ubiquitous. Where is `globset` being used that `log` isn't?

In an application/library (the latter to resolve #1909) that I'm working on, of course.

> As a downside, this infects every logging statement to the point of requiring conditional compilation. We could define our own logging macros to paper over this, but the juice really doesn't seem worth the squeeze given the number of other deps that `globset` already has.

It's true, but it doesn't seem like log statements have seen much action for a while, so I can't imagine this will be much of a maintenance burden. Happy to add a macro that hides the conditional compilation, however.

2022-06-05 01:22 UTC, SergioBenitez commented
> Happy to add a macro that hides the conditional compilation, however.

Just did this. I really want to see this merged. I see zero downside with a 25% reduction in the number of deps.

2022-06-05 01:37 UTC, BurntSushi requested changes
LGTM after a possible name change and a `rustfmt` run.

2022-06-05 01:37 UTC, BurntSushi commented on crates/globset/src/lib.rs
> +macro_rules! debug_log {
Can we just call this `debug!`?

2022-06-10 17:57 UTC, SergioBenitez commented
Done!

2022-06-10 18:09 UTC, BurntSushi approved these changes

2022-06-10 18:10 UTC, merged

2022-06-10 18:11 UTC, BurntSushi commented
This PR is in `globset 0.4.9` on crates.io.