Reduce `.crate` file size from 272 KB to 154 KB
BurntSushi/ripgrep pull request #1940
Opened 2021-07-19 23:44 UTC by Svetlitski

The `ripgrep` crate currently includes test data, benchmark results, continuous integration configuration, and a few other miscellaneous items in its `.crate` file, bloating its size significantly ([crates.io](https://crates.io/crates/ripgrep) shows it presently weighs in at 272 KB). The changes in this PR ensure that these files are excluded from the `.crate` file going forward.

2021-07-20 00:16 UTC, BurntSushi requested changes

2021-07-20 00:16 UTC, BurntSushi commented on Cargo.toml
> +exclude = ["HomebrewFormula", "/.github/", "/ci/", "/pkg/", "/tests/data/", "/benchsuite/", "/scripts/"]
Could you make sure we don't exceed 79 columns here? e.g.,

```toml
exclude = [
    "foo",
    "bar",
    ...
]
```

Also, please drop `/tests/data` from this list. Dropping that means you can't run tests using just the crate download.

Ignoring the rest looks sensible though. Thanks!

2021-07-20 00:45 UTC, Svetlitski commented
Requested changes have been made. The `.crate` file is now 168 KB if you were curious.

2022-03-18 23:29 UTC, Svetlitski commented
@BurntSushi Bump on this. I believe I made all the requested changes. Would appreciate a review when you find the time.

2023-07-08 18:28 UTC, BurntSushi approved these changes
Thanks!

2023-07-08 22:53 UTC, closed without merging