implemented filelist to get list of paths
BurntSushi/ripgrep pull request #2598
Opened 2023-08-25 23:55 UTC by eyalk11

Added option to get list of paths. I got into trouble trying to work with list of files in neovim (leaderf or other), when the list of files I wanted to search over was very long.  I believe it solves https://github.com/BurntSushi/ripgrep/issues/273 .

2023-08-29 03:03 UTC, BurntSushi commented
Thank you, but there are numerous issues with this PR as-is. The flag doesn't follow ripgrep's naming convention. Errors are squashed. The documentation for the flag is very insufficient. There are no tests. This also won't handle the case of file paths that contain invalid UTF-8. And perhaps more that I haven't noticed yet.

If you want to try to fix these things that would be great, but this is likely something I'll get to eventually myself if not.

2023-08-29 03:03 UTC, BurntSushi requested changes
Thank you, but there are numerous issues with this PR as-is. The flag doesn't follow ripgrep's naming convention. Errors are squashed. The documentation for the flag is very insufficient. There are no tests. This also won't handle the case of file paths that contain invalid UTF-8. And perhaps more that I haven't noticed yet.

If you want to try to fix these things that would be great, but this is likely something I'll get to eventually myself if not.

2023-08-30 23:25 UTC, eyalk11 commented
Thanks for the comment. I appreciate it. 

It was quick-and-a-bit-dirty patch . I don't really know rust (chatgpt wrote half of it) . 
I see what I can do. I can improve documentation and naming, but won't add tests. 
Also I already implemented it in my code with the naming as it is. 

I feel like in any case it would be better to leave it up to you.

2023-09-18 15:54 UTC, BurntSushi commented
OK, I'm going to close this out. I think this PR is pretty far from what this should ideally look like. I will very likely tackle this myself at some point.

2023-09-18 15:54 UTC, closed without merging